### ISSUE TITLE
Generate check object for all response codes (not 200 only)

### ISSUE THREAD

**Issue by JavierSierraBlazquez** [stepci/plugin-openapi#13]
Currently, when a response code is different than 200, the workflow generated will not contain check object, therefore the runner will not checking nor response code neither body.

I saw a specific condition for 200 in the code.
```
index.js line 167
if (swagger.paths[path][method].responses && swagger.paths[path][method].responses['200']) {
```
I wonder the reason of this and if there is something else I am missing. 

We are interested on contribute, so we could develop to handle multiple response codes. Any suggestion is welcome, of course.

**Comment by javier-sierra-sngular** [comment]
Hello @mishushakov, what do you think about this?

**Comment by mishushakov** [comment]
This is changed now
