### ISSUE TITLE
Error generating with a 200 response without content

### ISSUE THREAD

**Issue by adantoscano** [stepci/plugin-openapi#15]
Hi!

I'm getting a typeError trying to generate a workflow because of this line:

https://github.com/stepci/plugin-openapi/blob/1d67079c38837b246b8f41f29fe4f48625ada860/index.js#L168

I think this should have control if content exists before using it.

**Comment by mishushakov** [comment]
Cool, thanks for submitting the issue! Would you be able to open a pull request?
